### ISSUE TITLE
IE Toolbar Spy Heal Record Not Working

### ISSUE THREAD

**Issue by ghost** [CognizantQAHub/Cognizant-Intelligent-Test-Scripter-IE-Toolbar#7]
_From @phystem on July 7, 2017 13:59_

[x] bug report 

**Current behavior**
 - Open Spy/Heal/Recorder From IDE .
 - Open Internet Explorer
 - Make sure IE toolbar is Installed
 - Click on IE Toolbar Connection :warning: icon
 - Nothing is Happening

**Expected behavior**
- IE Toolbar Connection Icon Should change from :warning:  to :white_check_mark:

**Please tell us about your environment:**

* **OS :** 
Windows 7 32 bit

* **JAVA :** 
Java 1.8.131

_Copied from original issue: CognizantQAHub/Cognizant-Intelligent-Test-Scripter#45_

**Comment by ghost** [comment]
Changing the Jetty Version Dependency in **Extension Connect** module to **9.2.6.v20141205** works as of now. Have to pinpoint the issue further.

**Comment by ghost** [comment]
Exception is as follows

```
Fatal|WebSocket.connect:0|WebSocketSharp.WebSocketException: An error has occurred during a TLS handshake. ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The message received was unexpected or badly formatted
                              --- End of inner exception stack trace ---
	at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
        at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
        at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
        at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
        at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
        at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
        at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
        at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
        at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
        at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
        at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
        at WebSocketSharp.WebSocket.setClientStream()
 --- End of inner exception stack trace ---
        at WebSocketSharp.WebSocket.setClientStream()
        at WebSocketSharp.WebSocket.doHandshake()
        at WebSocketSharp.WebSocket.connect()
```
